name: Docker Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t docker-node-slim .
